In [2]:
import tensorflow as tf

In [3]:
# tf.ones()
a = tf.ones((2,2), tf.int32)
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [6]:
# tf.ones_like()
c = tf.Variable([[5,5,5],[6,7,8]])
b = tf.ones_like(c)
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [10]:
# tf.ones_initializer()
def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

In [12]:
d = ones_variable((4,4), tf.int32, tf.ones_initializer())
d

<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>