In [2]:
import tensorflow as tf

In [6]:
# create sparsetensor
# syntax = tf.sparse.SparseTensor(indices=2D array, values=1D, dense_shape=1D(row and columns))
a = tf.SparseTensor(indices=[[0,3],[1,3]], values=[4,7], dense_shape=[4,5])

In [7]:
# sparse tensor to dense sparse or np array
b = tf.sparse.to_dense(a)
b

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[0, 0, 0, 4, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [10]:
arr = b.numpy()
arr

array([[0, 0, 0, 4, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [11]:
# create arr to sparsetensor
c = tf.sparse.from_dense(arr)
c

SparseTensor(indices=tf.Tensor(
[[0 3]
 [1 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([4 7], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 5], shape=(2,), dtype=int64))

In [12]:
# access vlaue,indices,shape
c.values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 7], dtype=int32)>

In [13]:
c.indices

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 3],
       [1, 3]])>

In [14]:
c.dense_shape

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 5])>

In [15]:
# show in list
c.values.numpy().tolist()

[4, 7]

In [ ]:
# mathmatical operation like sum
tf.sparse.add(sparsetensor1, sparsetensor2)