# It works with list, tuple, scaler, Numpy array
tf variable/constant/placeholder/SparceMatrix with each other and with scaler and with list/tuple

In [2]:
import tensorflow as tf
import numpy as np

In [11]:
npa1 = np.array([1,4,3,9,5])
npa2 = np.array([2,2,3,4,5])
scaler = 10

In [12]:
# add
tf.add(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 3,  6,  6, 13, 10])>

In [13]:
# subtract
tf.subtract(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([-1,  2,  0,  5,  0])>

In [14]:
# multiply
tf.multiply(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 2,  8,  9, 36, 25])>

In [15]:
# divide
tf.divide(npa2,scaler)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.2, 0.2, 0.3, 0.4, 0.5])>

In [16]:
tf.divide(npa2,npa1)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([2.        , 0.5       , 1.        , 0.44444444, 1.        ])>

In [19]:
# sqrt
# int not supprt
npa3 = np.array([4.0,9.0,16.0])
tf.sqrt(npa3)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [20]:
# pow
tf.pow(npa1,3)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([  1,  64,  27, 729, 125])>

In [22]:
# maximum
tf.maximum(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 4, 3, 9, 5])>

In [23]:
# minimum
tf.minimum(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>