# assign int, str, float, array like constant but you can't change dype and shape only you can change value

In [31]:
import tensorflow as tf

In [32]:
a = tf.Variable([5,5,6,7])

In [33]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([5, 5, 6, 7], dtype=int32)>

In [34]:
# reshape variable
b = tf.reshape(a, (2,2))

In [35]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 5],
       [6, 7]], dtype=int32)>

In [36]:
# get index highest value
tf.argmax(b)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [37]:
tf.argmax(b).numpy()

array([1, 1])

In [38]:
c = [5,6,78,8]

In [39]:
# convert variable to tensor
d = tf.convert_to_tensor(c)
d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5,  6, 78,  8], dtype=int32)>

In [40]:
# change/assign new vlaue to tensor exiting memory
a.assign([10,4,5,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([10,  4,  5,  7], dtype=int32)>

In [41]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  4,  5,  7], dtype=int32)>

In [42]:
# assign variavle with new memory
a.assign_add([10,2,3,4])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([20,  6,  8, 11], dtype=int32)>

In [43]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([20,  6,  8, 11], dtype=int32)>